// components/ui/date-range-selector.tsx
"use client"

import { Calendar } from "lucide-react"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"

export const DATE_RANGES = [
  { label: "Last 7 days", value: "7d" },
  { label: "Last 30 days", value: "30d" },
  { label: "Last 3 months", value: "3m" },
  { label: "Last 6 months", value: "6m" },
  { label: "Last year", value: "1y" },
  { label: "All time", value: "all" },
]

interface DateRangeSelectorProps {
  value: string
  onChange: (value: string) => void
  ranges?: { label: string; value: string }[]
}

export function DateRangeSelector({ value, onChange, ranges = DATE_RANGES }: DateRangeSelectorProps) {
  return (
    <div className="flex items-center gap-2">
      <Calendar className="h-4 w-4 text-muted-foreground" />
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger className="w-[140px]">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {ranges.map((range) => (
            <SelectItem key={range.value} value={range.value}>
              {range.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  )
}

// vue_components/ui/DateRangeSelector.vue
<script setup lang="ts">
import Calendar from 'lucide-vue-next/dist/esm/icons/calendar'
import Select from './Select.vue'
import SelectContent from './SelectContent.vue'
import SelectItem from './SelectItem.vue'
import SelectTrigger from './SelectTrigger.vue'
import SelectValue from './SelectValue.vue'
const props = defineProps<{ value: string; ranges?: { label: string; value: string }[] }>()
const emit = defineEmits<{ (e:'update:value', v:string): void }>()
const options = props.ranges || [
  { label: 'Last 7 days', value: '7d' },
  { label: 'Last 30 days', value: '30d' },
  { label: 'Last 3 months', value: '3m' },
  { label: 'Last 6 months', value: '6m' },
  { label: 'Last year', value: '1y' },
  { label: 'All time', value: 'all' },
]
</script>
<template>
  <div class="flex items-center gap-2">
    <Calendar class="h-4 w-4 text-muted-foreground" />
    <Select :modelValue="props.value" @update:modelValue="v=>emit('update:value', v)">
      <SelectTrigger class="w-[140px]">
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        <SelectItem v-for="opt in options" :key="opt.value" :value="opt.value">{{ opt.label }}</SelectItem>
      </SelectContent>
    </Select>
  </div>
</template>
