// vue_components/common/FiltersDropdown.vue
<script lang="ts" setup>
import { Filter, X } from 'lucide-vue-next'
import Button from '../ui/Button.vue'
import DropdownMenu from '../ui/DropdownMenu.vue'
import DropdownMenuTrigger from '../ui/DropdownMenuTrigger.vue'
import DropdownMenuContent from '../ui/DropdownMenuContent.vue'
import DropdownMenuLabel from '../ui/DropdownMenuLabel.vue'
import DropdownMenuSeparator from '../ui/DropdownMenuSeparator.vue'
import Checkbox from '../ui/Checkbox.vue'
import Label from '../ui/Label.vue'
import Badge from '../ui/Badge.vue'
const props = defineProps<{ filters: Record<string,string[]>; activeFilters: Record<string,string[]>; onFiltersChange: (f:Record<string,string[]>)=>void }>()
function handleFilterChange(cat:string, value:string, checked:boolean){
  const newFilters = { ...props.activeFilters }
  if(!newFilters[cat]) newFilters[cat] = []
  if(checked) newFilters[cat] = [...newFilters[cat], value]
  else newFilters[cat] = newFilters[cat].filter(v => v!==value)
  if(newFilters[cat].length===0) delete newFilters[cat]
  props.onFiltersChange(newFilters)
}
function clearAll(){ props.onFiltersChange({}) }
const activeCount = Object.values(props.activeFilters).flat().length
</script>
<template>
  <div class="flex items-center gap-2">
    <DropdownMenu>
      <DropdownMenuTrigger as-child>
        <Button variant="outline" class="relative">
          <Filter class="mr-2 h-4 w-4" />
          Filters
          <Badge v-if="activeCount>0" variant="secondary" class="ml-2 h-5 w-5 rounded-full p-0 text-xs">{{ activeCount }}</Badge>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent class="w-64" align="end">
        <div class="flex items-center justify-between p-2">
          <DropdownMenuLabel class="p-0">Filters</DropdownMenuLabel>
          <Button v-if="activeCount>0" variant="ghost" size="sm" @click="clearAll">Clear all</Button>
        </div>
        <DropdownMenuSeparator />
        <div v-for="(values,category) in props.filters" :key="category" class="p-2">
          <Label class="text-sm font-medium capitalize">{{ category }}</Label>
          <div class="mt-2 space-y-2">
            <div v-for="value in values" :key="value" class="flex items-center space-x-2">
              <Checkbox :id="`${category}-${value}`" :checked="props.activeFilters[category]?.includes(value) || false" @update:checked="val => handleFilterChange(category,value,val as boolean)" />
              <Label :for="`${category}-${value}`" class="text-sm">{{ value }}</Label>
            </div>
          </div>
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
    <template v-for="(values,category) in props.activeFilters">
      <Badge v-for="value in values" :key="`${category}-${value}`" variant="secondary" class="gap-1">
        {{ value }}
        <X class="h-3 w-3 cursor-pointer" @click="handleFilterChange(category,value,false)" />
      </Badge>
    </template>
  </div>
</template>

// components/common/filters-dropdown.tsx
"use client"

import { Filter, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"

interface FiltersDropdownProps {
  filters: {
    [key: string]: string[]
  }
  activeFilters: {
    [key: string]: string[]
  }
  onFiltersChange: (filters: { [key: string]: string[] }) => void
}

export function FiltersDropdown({ filters, activeFilters, onFiltersChange }: FiltersDropdownProps) {
  const handleFilterChange = (category: string, value: string, checked: boolean) => {
    const newFilters = { ...activeFilters }
    if (!newFilters[category]) {
      newFilters[category] = []
    }

    if (checked) {
      newFilters[category] = [...newFilters[category], value]
    } else {
      newFilters[category] = newFilters[category].filter((item) => item !== value)
    }

    if (newFilters[category].length === 0) {
      delete newFilters[category]
    }

    onFiltersChange(newFilters)
  }

  const clearAllFilters = () => {
    onFiltersChange({})
  }

  const activeFilterCount = Object.values(activeFilters).flat().length

  return (
    <div className="flex items-center gap-2">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="relative">
            <Filter className="mr-2 h-4 w-4" />
            Filters
            {activeFilterCount > 0 && (
              <Badge variant="secondary" className="ml-2 h-5 w-5 rounded-full p-0 text-xs">
                {activeFilterCount}
              </Badge>
            )}
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent className="w-64" align="end">
          <div className="flex items-center justify-between p-2">
            <DropdownMenuLabel className="p-0">Filters</DropdownMenuLabel>
            {activeFilterCount > 0 && (
              <Button variant="ghost" size="sm" onClick={clearAllFilters}>
                Clear all
              </Button>
            )}
          </div>
          <DropdownMenuSeparator />
          {Object.entries(filters).map(([category, values]) => (
            <div key={category} className="p-2">
              <Label className="text-sm font-medium capitalize">{category}</Label>
              <div className="mt-2 space-y-2">
                {values.map((value) => (
                  <div key={value} className="flex items-center space-x-2">
                    <Checkbox
                      id={`${category}-${value}`}
                      checked={activeFilters[category]?.includes(value) || false}
                      onCheckedChange={(checked) => handleFilterChange(category, value, checked as boolean)}
                    />
                    <Label htmlFor={`${category}-${value}`} className="text-sm">
                      {value}
                    </Label>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>

      {/* Active Filters */}
      {Object.entries(activeFilters).map(([category, values]) =>
        values.map((value) => (
          <Badge key={`${category}-${value}`} variant="secondary" className="gap-1">
            {value}
            <X className="h-3 w-3 cursor-pointer" onClick={() => handleFilterChange(category, value, false)} />
          </Badge>
        )),
      )}
    </div>
  )
}
