// vue_components/common/PageHeader.vue
<script lang="ts" setup>
import ActionButton from './ActionButton.vue'
const props = defineProps<{ title: string; description?: string; action?: { label: string; onClick: () => void; icon?: any } }>()
</script>
<template>
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold">{{ props.title }}</h1>
      <p v-if="props.description" class="text-muted-foreground">{{ props.description }}</p>
    </div>
    <ActionButton v-if="props.action" :onClick="props.action.onClick" :icon="props.action.icon">
      {{ props.action.label }}
    </ActionButton>
  </div>
</template>

// components/common/page-header.tsx
"use client"

import { ActionButton } from "./action-button"
import type { LucideIcon } from "lucide-react"

interface PageHeaderProps {
  title: string
  description?: string
  action?: {
    label: string
    onClick: () => void
    icon?: LucideIcon
  }
}

export function PageHeader({ title, description, action }: PageHeaderProps) {
  return (
    <div className="flex items-center justify-between">
      <div>
        <h1 className="text-3xl font-bold">{title}</h1>
        {description && <p className="text-muted-foreground">{description}</p>}
      </div>
      {action && (
        <ActionButton onClick={action.onClick} icon={action.icon}>
          {action.label}
        </ActionButton>
      )}
    </div>
  )
}
