// vue_components/common/SearchInput.vue
<script lang="ts" setup>
import { Search } from 'lucide-vue-next'
import Input from '../ui/Input.vue'
const props = defineProps<{ value: string; placeholder?: string; class?: string }>()
const emit = defineEmits<{ (e:'update:value', value: string): void }>()
function onInput(e: Event) {
  emit('update:value', (e.target as HTMLInputElement).value)
}
</script>
<template>
  <div :class="`relative flex-1 max-w-md ${props.class || ''}`">
    <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
    <Input class="pl-10" :placeholder="props.placeholder || 'Search...'" :value="props.value" @input="onInput" />
  </div>
</template>

// components/common/search-input.tsx
"use client"

import { Search } from "lucide-react"
import { Input } from "@/components/ui/input"

interface SearchInputProps {
  value: string
  onChange: (value: string) => void
  placeholder?: string
  className?: string
}

export function SearchInput({ value, onChange, placeholder = "Search...", className }: SearchInputProps) {
  return (
    <div className={`relative flex-1 max-w-md ${className}`}>
      <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
      <Input placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} className="pl-10" />
    </div>
  )
}
