// vue_components/AppSidebar.vue
<script lang="ts" setup>
import { MessageSquare, BarChart3, Users, Database, Settings, Clock } from 'lucide-vue-next'
import NavMain from './NavMain.vue'
import NavUser from './NavUser.vue'
import TeamSwitcher from './TeamSwitcher.vue'
import Sidebar from './ui/Sidebar.vue'
import SidebarHeader from './ui/SidebarHeader.vue'
import SidebarContent from './ui/SidebarContent.vue'
import SidebarFooter from './ui/SidebarFooter.vue'
import SidebarRail from './ui/SidebarRail.vue'

const data = {
  teams: [ { name: 'A2P Platform', logo: MessageSquare, plan: 'Enterprise' } ],
  navMain: [
    { title: 'Dashboard', url: '/dashboard', icon: BarChart3, isActive: true },
    { title: 'Partner Settings', url: '#', icon: Users, items: [
        { title: 'AN Patterns', url: '/an-patterns' },
        { title: 'Aplhanames', url: '/alphanames' },
        { title: 'CTNs', url: '/ctns' },
        { title: 'Partners', url: '/partners' },
        { title: 'Partners Statistics', url: '/partners-statistics' },
        { title: 'SHN Patterns', url: '/shn-patterns' },
        { title: 'Short numbers', url: '/short-numbers' },
    ]},
    { title: 'Logs', url: '#', icon: Database, items: [
        { title: 'Audit Logs', url: '/audit-logs' },
        { title: 'MO Interceptor logs', url: '/mo-interceptor-logs' },
        { title: 'MT Interceptor Logs', url: '/mt-interceptor-logs' },
        { title: 'Spams', url: '/spams' },
    ]},
    { title: 'Categories', url: '#', icon: BarChart3, items: [
        { title: 'Category MT', url: '/category-mt' },
        { title: 'Category Statistics', url: '/category-statistics' },
    ]},
    { title: 'SM', url: '#', icon: MessageSquare, items: [
        { title: 'Deliver SM (DLR)', url: '/deliver-sm-dlr' },
        { title: 'Deliver SM (P2A)', url: '/deliver-sm-p2a' },
        { title: 'Submit SM', url: '/submit-sm' },
        { title: 'Submit SM Response', url: '/submit-sm-response' },
    ]},
    { title: 'System Settings', url: '#', icon: Settings, items: [
        { title: 'Groups', url: '/groups' },
        { title: 'CDR Settings', url: '/cdr-settings' },
        { title: 'Custom users', url: '/custom-users' },
        { title: 'Sites', url: '/sites' },
        { title: 'Regex Patterns', url: '/regex-patterns' },
    ]},
    { title: 'Periodic Tasks', url: '#', icon: Clock, items: [
        { title: 'Clocked', url: '/periodic-tasks/clocked' },
        { title: 'Crontabs', url: '/periodic-tasks/crontabs' },
        { title: 'Intervals', url: '/periodic-tasks/intervals' },
        { title: 'Periodic tasks', url: '/periodic-tasks/periodic-tasks' },
        { title: 'Solar events', url: '/periodic-tasks/solar-events' },
    ]},
    { title: 'Messages', url: '#', icon: MessageSquare, items: [
        { title: 'MO Messages', url: '/mo-messages' },
        { title: 'MT Messages', url: '/mt-messages' },
    ]},
  ]
}
</script>
<template>
  <Sidebar collapsible="offcanvas">
    <SidebarHeader>
      <TeamSwitcher :teams="data.teams" />
    </SidebarHeader>
    <SidebarContent>
      <NavMain :items="data.navMain" />
    </SidebarContent>
    <SidebarFooter>
      <NavUser />
    </SidebarFooter>
    <SidebarRail />
  </Sidebar>
</template>

// components/app-sidebar.tsx
"use client"

import type * as React from "react"
import {
  Database,
  FileText,
  Settings,
  Users,
  MessageSquare,
  Shield,
  BarChart3,
  Clock,
  Globe,
  Hash,
  Phone,
} from "lucide-react"

import { NavMain } from "@/components/nav-main"
import { NavUser } from "@/components/nav-user"
import { TeamSwitcher } from "@/components/team-switcher"
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarRail } from "@/components/ui/sidebar"

const data = {
  teams: [
    {
      name: "A2P Platform",
      logo: MessageSquare,
      plan: "Enterprise",
    },
  ],
  navMain: [
    {
      title: "Dashboard",
      url: "/dashboard",
      icon: BarChart3,
      isActive: true,
    },
    {
      title: "Groups",
      url: "#",
      icon: Users,
      items: [
        {
          title: "Main",
          url: "/groups/main",
        },
      ],
    },
    {
      title: "AN Patterns",
      url: "/an-patterns",
      icon: Hash,
    },
    {
      title: "Alphanames",
      url: "/alphanames",
      icon: FileText,
    },
    {
      title: "Audit Logs",
      url: "/audit-logs",
      icon: Shield,
    },
    {
      title: "CDR Settings",
      url: "/cdr-settings",
      icon: Settings,
    },
    {
      title: "CTNs",
      url: "/ctns",
      icon: Phone,
    },
    {
      title: "Category MT",
      url: "/category-mt",
      icon: BarChart3,
    },
    {
      title: "Category Statistics",
      url: "/category-statistics",
      icon: BarChart3,
    },
    {
      title: "Custom users",
      url: "/custom-users",
      icon: Users,
    },
    {
      title: "Deliver SM (DLR)",
      url: "/deliver-sm-dlr",
      icon: MessageSquare,
    },
    {
      title: "Deliver SM (P2A)",
      url: "/deliver-sm-p2a",
      icon: MessageSquare,
    },
    {
      title: "MO Interceptor logs",
      url: "/mo-interceptor-logs",
      icon: Database,
    },
    {
      title: "MO Messages",
      url: "/mo-messages",
      icon: MessageSquare,
    },
    {
      title: "MT Interceptor Logs",
      url: "/mt-interceptor-logs",
      icon: Database,
    },
    {
      title: "MT Messages",
      url: "/mt-messages",
      icon: MessageSquare,
    },
    {
      title: "Partners",
      url: "/partners",
      icon: Users,
    },
    {
      title: "Partners Statistics",
      url: "/partners-statistics",
      icon: BarChart3,
    },
    {
      title: "Regex Patterns",
      url: "/regex-patterns",
      icon: Hash,
    },
    {
      title: "SHN Patterns",
      url: "/shn-patterns",
      icon: Hash,
    },
    {
      title: "Short numbers",
      url: "/short-numbers",
      icon: Phone,
    },
    {
      title: "Spams",
      url: "/spams",
      icon: Shield,
    },
    {
      title: "Submit SM",
      url: "/submit-sm",
      icon: MessageSquare,
    },
    {
      title: "Submit SM Response",
      url: "/submit-sm-response",
      icon: MessageSquare,
    },
    {
      title: "Periodic Tasks",
      url: "#",
      icon: Clock,
      items: [
        {
          title: "Clocked",
          url: "/periodic-tasks/clocked",
        },
        {
          title: "Crontabs",
          url: "/periodic-tasks/crontabs",
        },
        {
          title: "Intervals",
          url: "/periodic-tasks/intervals",
        },
        {
          title: "Periodic tasks",
          url: "/periodic-tasks/periodic-tasks",
        },
        {
          title: "Solar events",
          url: "/periodic-tasks/solar-events",
        },
      ],
    },
    {
      title: "Sites",
      url: "#",
      icon: Globe,
      items: [
        {
          title: "Sites",
          url: "/sites/sites",
        },
      ],
    },
  ],
}

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  return (
    <Sidebar collapsible="offcanvas" {...props}>
      <SidebarHeader>
        <TeamSwitcher teams={data.teams} />
      </SidebarHeader>
      <SidebarContent>
        <NavMain items={data.navMain} />
      </SidebarContent>
      <SidebarFooter>
        <NavUser />
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  )
}
