// vue_components/EnhancedDatePicker.vue
<script lang="ts" setup>
import { ref, watch } from 'vue'
import Calendar from './ui/Calendar.vue'
import Button from './ui/Button.vue'
import Input from './ui/Input.vue'
import Label from './ui/Label.vue'
import Popover from './ui/Popover.vue'
import PopoverTrigger from './ui/PopoverTrigger.vue'
import PopoverContent from './ui/PopoverContent.vue'
import { CalendarIcon, RotateCcw } from 'lucide-vue-next'
import { format, parse, isValid, subDays, startOfDay, endOfDay } from 'date-fns'

const props = defineProps<{ from?: Date; to?: Date; onDateChange: (from?: Date, to?: Date) => void; class?: string }>()

const presets = [
  { label: 'Today', getValue: () => ({ from: startOfDay(new Date()), to: endOfDay(new Date()) }) },
  { label: 'Yesterday', getValue: () => ({ from: startOfDay(subDays(new Date(),1)), to: endOfDay(subDays(new Date(),1)) }) },
  { label: 'Last 7 days', getValue: () => ({ from: startOfDay(subDays(new Date(),6)), to: endOfDay(new Date()) }) },
  { label: 'Last 30 days', getValue: () => ({ from: startOfDay(subDays(new Date(),29)), to: endOfDay(new Date()) }) },
  { label: 'This month', getValue: () => ({ from: startOfDay(subDays(new Date(), new Date().getDate()-1)), to: endOfDay(new Date()) }) }
]

const fromOpen = ref(false)
const toOpen = ref(false)
const fromInput = ref(props.from ? format(props.from,'yyyy-MM-dd') : '')
const toInput = ref(props.to ? format(props.to,'yyyy-MM-dd') : '')

watch(() => props.from, v => { fromInput.value = v ? format(v,'yyyy-MM-dd') : '' })
watch(() => props.to, v => { toInput.value = v ? format(v,'yyyy-MM-dd') : '' })

function handleFromInputChange(value:string){
  fromInput.value = value
  if(value){ const d = parse(value,'yyyy-MM-dd', new Date()); if(isValid(d)) props.onDateChange(startOfDay(d), props.to) }
  else props.onDateChange(undefined, props.to)
}
function handleToInputChange(value:string){
  toInput.value = value
  if(value){ const d = parse(value,'yyyy-MM-dd', new Date()); if(isValid(d)) props.onDateChange(props.from, endOfDay(d)) }
  else props.onDateChange(props.from, undefined)
}
function handlePreset(p:{label:string; getValue:()=>{from:Date,to:Date}}){ const {from,to} = p.getValue(); props.onDateChange(from,to) }
function handleReset(){ props.onDateChange(undefined,undefined) }
</script>
<template>
  <div :class="['space-y-4', props.class]">
    <div class="flex flex-wrap gap-2">
      <Button v-for="preset in presets" :key="preset.label" variant="outline" size="sm" class="text-xs" @click="handlePreset(preset)">{{ preset.label }}</Button>
      <Button variant="outline" size="sm" class="text-xs" @click="handleReset"><RotateCcw class="w-3 h-3 mr-1" />Reset</Button>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="space-y-2">
        <Label class="text-sm font-medium">From Date</Label>
        <div class="flex gap-2">
          <div class="flex-1"><Input type="date" :value="fromInput" @input="e=>handleFromInputChange((e.target as HTMLInputElement).value)" /></div>
          <Popover :open="fromOpen" @update:open="v=>fromOpen=v">
            <PopoverTrigger as-child>
              <Button variant="outline" size="icon"><CalendarIcon class="h-4 w-4" /></Button>
            </PopoverTrigger>
            <PopoverContent class="w-auto p-0" align="start">
              <Calendar @change="d=>{ if(d) props.onDateChange(startOfDay(d as any), props.to); fromInput = format(d as any,'yyyy-MM-dd'); fromOpen=false }" />
            </PopoverContent>
          </Popover>
        </div>
      </div>
      <div class="space-y-2">
        <Label class="text-sm font-medium">To Date</Label>
        <div class="flex gap-2">
          <div class="flex-1"><Input type="date" :value="toInput" @input="e=>handleToInputChange((e.target as HTMLInputElement).value)" /></div>
          <Popover :open="toOpen" @update:open="v=>toOpen=v">
            <PopoverTrigger as-child>
              <Button variant="outline" size="icon"><CalendarIcon class="h-4 w-4" /></Button>
            </PopoverTrigger>
            <PopoverContent class="w-auto p-0" align="start">
              <Calendar @change="d=>{ if(d) props.onDateChange(props.from, endOfDay(d as any)); toInput = format(d as any,'yyyy-MM-dd'); toOpen=false }" />
            </PopoverContent>
          </Popover>
        </div>
      </div>
    </div>
    <div v-if="props.from && props.to" class="p-3 bg-muted border rounded-lg">
      <div class="flex items-center gap-2 text-sm">
        <CalendarIcon class="w-4 h-4" />
        <span class="font-medium">Selected Range:</span>
        <span>{{ format(props.from,'MMM dd, yyyy') }} - {{ format(props.to,'MMM dd, yyyy') }}</span>
      </div>
    </div>
  </div>
</template>

// components/enhanced-date-picker.tsx
"use client"

import { useState, useEffect } from "react"
import { Calendar } from "@/components/ui/calendar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { CalendarIcon, RotateCcw } from "lucide-react"
import { format, parse, isValid, subDays, startOfDay, endOfDay } from "date-fns"

interface EnhancedDatePickerProps {
  from?: Date
  to?: Date
  onDateChange: (from?: Date, to?: Date) => void
  className?: string
}

const presets = [
  { label: "Today", getValue: () => ({ from: startOfDay(new Date()), to: endOfDay(new Date()) }) },
  {
    label: "Yesterday",
    getValue: () => ({ from: startOfDay(subDays(new Date(), 1)), to: endOfDay(subDays(new Date(), 1)) }),
  },
  { label: "Last 7 days", getValue: () => ({ from: startOfDay(subDays(new Date(), 6)), to: endOfDay(new Date()) }) },
  { label: "Last 30 days", getValue: () => ({ from: startOfDay(subDays(new Date(), 29)), to: endOfDay(new Date()) }) },
  {
    label: "This month",
    getValue: () => ({ from: startOfDay(subDays(new Date(), new Date().getDate() - 1)), to: endOfDay(new Date()) }),
  },
]

export function EnhancedDatePicker({ from, to, onDateChange, className }: EnhancedDatePickerProps) {
  const [fromOpen, setFromOpen] = useState(false)
  const [toOpen, setToOpen] = useState(false)
  const [fromInput, setFromInput] = useState(from ? format(from, "yyyy-MM-dd") : "")
  const [toInput, setToInput] = useState(to ? format(to, "yyyy-MM-dd") : "")

  useEffect(() => {
    setFromInput(from ? format(from, "yyyy-MM-dd") : "")
    setToInput(to ? format(to, "yyyy-MM-dd") : "")
  }, [from, to])

  const handleFromInputChange = (value: string) => {
    setFromInput(value)
    if (value) {
      const parsedDate = parse(value, "yyyy-MM-dd", new Date())
      if (isValid(parsedDate)) {
        onDateChange(startOfDay(parsedDate), to)
      }
    } else {
      onDateChange(undefined, to)
    }
  }

  const handleToInputChange = (value: string) => {
    setToInput(value)
    if (value) {
      const parsedDate = parse(value, "yyyy-MM-dd", new Date())
      if (isValid(parsedDate)) {
        onDateChange(from, endOfDay(parsedDate))
      }
    } else {
      onDateChange(from, undefined)
    }
  }

  const handleFromCalendarSelect = (date: Date | undefined) => {
    if (date) {
      onDateChange(startOfDay(date), to)
      setFromInput(format(date, "yyyy-MM-dd"))
    }
    setFromOpen(false)
  }

  const handleToCalendarSelect = (date: Date | undefined) => {
    if (date) {
      onDateChange(from, endOfDay(date))
      setToInput(format(date, "yyyy-MM-dd"))
    }
    setToOpen(false)
  }

  const handlePresetClick = (preset: (typeof presets)[0]) => {
    const { from: presetFrom, to: presetTo } = preset.getValue()
    onDateChange(presetFrom, presetTo)
  }

  const handleReset = () => {
    onDateChange(undefined, undefined)
  }

  return (
    <div className={`space-y-4 ${className}`}>
      {/* Presets */}
      <div className="flex flex-wrap gap-2">
        {presets.map((preset) => (
          <Button
            key={preset.label}
            variant="outline"
            size="sm"
            onClick={() => handlePresetClick(preset)}
            className="text-xs"
          >
            {preset.label}
          </Button>
        ))}
        <Button
          variant="outline"
          size="sm"
          onClick={handleReset}
          className="text-xs"
        >
          <RotateCcw className="w-3 h-3 mr-1" />
          Reset
        </Button>
      </div>

      {/* Date Inputs */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* From Date */}
        <div className="space-y-2">
          <Label className="text-sm font-medium">From Date</Label>
          <div className="flex gap-2">
            <div className="flex-1">
              <Input
                type="date"
                value={fromInput}
                onChange={(e) => handleFromInputChange(e.target.value)}
              />
            </div>
            <Popover open={fromOpen} onOpenChange={setFromOpen}>
              <PopoverTrigger asChild>
                <Button variant="outline" size="icon">
                  <CalendarIcon className="h-4 w-4" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar mode="single" selected={from} onSelect={handleFromCalendarSelect} initialFocus />
              </PopoverContent>
            </Popover>
          </div>
        </div>

        {/* To Date */}
        <div className="space-y-2">
          <Label className="text-sm font-medium">To Date</Label>
          <div className="flex gap-2">
            <div className="flex-1">
              <Input
                type="date"
                value={toInput}
                onChange={(e) => handleToInputChange(e.target.value)}
              />
            </div>
            <Popover open={toOpen} onOpenChange={setToOpen}>
              <PopoverTrigger asChild>
                <Button variant="outline" size="icon">
                  <CalendarIcon className="h-4 w-4" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar mode="single" selected={to} onSelect={handleToCalendarSelect} initialFocus />
              </PopoverContent>
            </Popover>
          </div>
        </div>
      </div>

      {/* Selected Range Display */}
      {from && to && (
        <div className="p-3 bg-muted border rounded-lg">
          <div className="flex items-center gap-2 text-sm">
            <CalendarIcon className="w-4 h-4" />
            <span className="font-medium">Selected Range:</span>
            <span>
              {format(from, "MMM dd, yyyy")} - {format(to, "MMM dd, yyyy")}
            </span>
          </div>
        </div>
      )}
    </div>
  )
}
