// vue_components/NavMain.vue
<script lang="ts" setup>
import { ChevronRight } from 'lucide-vue-next'
import Collapsible from './ui/Collapsible.vue'
import CollapsibleContent from './ui/CollapsibleContent.vue'
import CollapsibleTrigger from './ui/CollapsibleTrigger.vue'
import SidebarGroup from './ui/SidebarGroup.vue'
import SidebarGroupLabel from './ui/SidebarGroupLabel.vue'
import SidebarMenu from './ui/SidebarMenu.vue'
import SidebarMenuButton from './ui/SidebarMenuButton.vue'
import SidebarMenuItem from './ui/SidebarMenuItem.vue'
import SidebarMenuSub from './ui/SidebarMenuSub.vue'
import SidebarMenuSubButton from './ui/SidebarMenuSubButton.vue'
import SidebarMenuSubItem from './ui/SidebarMenuSubItem.vue'

const props = defineProps<{ items: { title: string; url: string; icon?: any; isActive?: boolean; items?: { title: string; url: string }[] }[] }>()
</script>
<template>
  <SidebarGroup>
    <SidebarGroupLabel>Platform</SidebarGroupLabel>
    <SidebarMenu>
      <template v-for="item in props.items" :key="item.title">
        <Collapsible as-child :default-open="item.isActive" class="group/collapsible">
          <SidebarMenuItem>
            <template v-if="item.items && item.items.length">
              <CollapsibleTrigger as-child>
                <SidebarMenuButton :isActive="item.isActive">
                  <component v-if="item.icon" :is="item.icon" />
                  <span>{{ item.title }}</span>
                  <ChevronRight class="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
                </SidebarMenuButton>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <SidebarMenuSub>
                  <SidebarMenuSubItem v-for="sub in item.items" :key="sub.title">
                    <SidebarMenuSubButton :isActive="false" as-child>
                      <a :href="sub.url"><span>{{ sub.title }}</span></a>
                    </SidebarMenuSubButton>
                  </SidebarMenuSubItem>
                </SidebarMenuSub>
              </CollapsibleContent>
            </template>
            <template v-else>
              <SidebarMenuButton :isActive="item.isActive" as-child>
                <a :href="item.url">
                  <component v-if="item.icon" :is="item.icon" />
                  <span>{{ item.title }}</span>
                </a>
              </SidebarMenuButton>
            </template>
          </SidebarMenuItem>
        </Collapsible>
      </template>
    </SidebarMenu>
  </SidebarGroup>
</template>

// components/nav-main.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { ChevronRight, type LucideIcon } from "lucide-react"

import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from "@/components/ui/sidebar"

export function NavMain({
  items,
}: {
  items: {
    title: string
    url: string
    icon?: LucideIcon
    isActive?: boolean
    items?: {
      title: string
      url: string
    }[]
  }[]
}) {
  const pathname = usePathname()

  return (
    <SidebarGroup>
      <SidebarGroupLabel>Platform</SidebarGroupLabel>
      <SidebarMenu>
        {items.map((item) => {
          const isActive = pathname === item.url || pathname.startsWith(item.url + "/")
          const hasSubItems = item.items && item.items.length > 0

          return (
            <Collapsible key={item.title} asChild defaultOpen={isActive} className="group/collapsible">
              <SidebarMenuItem>
                {hasSubItems ? (
                  <CollapsibleTrigger asChild>
                    <SidebarMenuButton tooltip={item.title} isActive={isActive}>
                      {item.icon && <item.icon />}
                      <span>{item.title}</span>
                      <ChevronRight className="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
                    </SidebarMenuButton>
                  </CollapsibleTrigger>
                ) : (
                  <SidebarMenuButton asChild tooltip={item.title} isActive={isActive}>
                    <Link href={item.url}>
                      {item.icon && <item.icon />}
                      <span>{item.title}</span>
                    </Link>
                  </SidebarMenuButton>
                )}
                {hasSubItems && (
                  <CollapsibleContent>
                    <SidebarMenuSub>
                      {item.items?.map((subItem) => {
                        const isSubActive = pathname === subItem.url || pathname.startsWith(subItem.url + "/")
                        return (
                          <SidebarMenuSubItem key={subItem.title}>
                            <SidebarMenuSubButton asChild isActive={isSubActive}>
                              <Link href={subItem.url}>
                                <span>{subItem.title}</span>
                              </Link>
                            </SidebarMenuSubButton>
                          </SidebarMenuSubItem>
                        )
                      })}
                    </SidebarMenuSub>
                  </CollapsibleContent>
                )}
              </SidebarMenuItem>
            </Collapsible>
          )
        })}
      </SidebarMenu>
    </SidebarGroup>
  )
}
