// vue_components/auth/ProtectedRoute.vue
<script lang="ts" setup>
import LoadingSpinner from '../common/LoadingSpinner.vue'
const props = defineProps<{ isAuthenticated?: boolean; isLoading?: boolean }>()
</script>
<template>
  <div v-if="props.isLoading" class="min-h-screen flex items-center justify-center">
    <LoadingSpinner size="lg" />
  </div>
  <template v-else-if="props.isAuthenticated">
    <slot />
  </template>
</template>

// components/auth/protected-route.tsx
"use client"

import type React from "react"

import { useAuth } from "@/contexts/auth-context"
import { LoadingSpinner } from "@/components/common/loading-spinner"
import { useRouter } from "next/navigation"
import { useEffect } from "react"

interface ProtectedRouteProps {
  children: React.ReactNode
}

export function ProtectedRoute({ children }: ProtectedRouteProps) {
  const { isAuthenticated, isLoading } = useAuth()
  const router = useRouter()

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push("/login")
    }
  }, [isAuthenticated, isLoading, router])

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <LoadingSpinner size="lg" />
      </div>
    )
  }

  if (!isAuthenticated) {
    return null
  }

  return <>{children}</>
}
